name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Install Chrome and ChromeDriver
      run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          sudo apt-get install -y chromium-browser
          export CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Detected Chrome version: $CHROME_VERSION"
          wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/$(echo $CHROME_VERSION | cut -d '.' -f 1-3)/chromedriver_linux64.zip || wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/$(echo $CHROME_VERSION | cut -d '.' -f 1)/chromedriver_linux64.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version
          
    - name: Build and Run Cucumber Tests with Maven
      run: mvn clean verify

